development:
  adapter: postgresql
  database: airbrake_to_pushover_api_development
  username: user
  password: 
  host: localhost

test:
  adapter: postgresql
  database: airbrake_to_pushover_api_test
  username: user
  password: 
  host: localhost
